/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_autoref_jnisample_NativeMethod */

#ifndef _Included_cn_autoref_jnisample_NativeMethod
#define _Included_cn_autoref_jnisample_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_autoref_jnisample_NativeMethod
 * Method:    getHelloJniText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_autoref_jnisample_NativeMethod_getHelloJniText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
